// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: grpc/chitchat.proto

package chitchat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_CHAT  MessageType = 0
	MessageType_JOIN  MessageType = 1
	MessageType_LEAVE MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "CHAT",
		1: "JOIN",
		2: "LEAVE",
	}
	MessageType_value = map[string]int32{
		"CHAT":  0,
		"JOIN":  1,
		"LEAVE": 2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_chitchat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_grpc_chitchat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_chitchat_proto_rawDescGZIP(), []int{0}
}

type JoinRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName  string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	LogicalTimestamp int64                  `protobuf:"varint,2,opt,name=logical_timestamp,json=logicalTimestamp,proto3" json:"logical_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_grpc_chitchat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chitchat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_grpc_chitchat_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *JoinRequest) GetLogicalTimestamp() int64 {
	if x != nil {
		return x.LogicalTimestamp
	}
	return 0
}

type LeaveRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName  string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	LogicalTimestamp int64                  `protobuf:"varint,2,opt,name=logical_timestamp,json=logicalTimestamp,proto3" json:"logical_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_grpc_chitchat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chitchat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_grpc_chitchat_proto_rawDescGZIP(), []int{1}
}

func (x *LeaveRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *LeaveRequest) GetLogicalTimestamp() int64 {
	if x != nil {
		return x.LogicalTimestamp
	}
	return 0
}

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParticipantName  string                 `protobuf:"bytes,1,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LogicalTimestamp int64                  `protobuf:"varint,3,opt,name=logical_timestamp,json=logicalTimestamp,proto3" json:"logical_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_grpc_chitchat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chitchat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_chitchat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetParticipantName() string {
	if x != nil {
		return x.ParticipantName
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetLogicalTimestamp() int64 {
	if x != nil {
		return x.LogicalTimestamp
	}
	return 0
}

type BroadcastMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SenderName       string                 `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	LogicalTimestamp int64                  `protobuf:"varint,2,opt,name=logical_timestamp,json=logicalTimestamp,proto3" json:"logical_timestamp,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType      MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=chitchat.MessageType" json:"message_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BroadcastMessage) Reset() {
	*x = BroadcastMessage{}
	mi := &file_grpc_chitchat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessage) ProtoMessage() {}

func (x *BroadcastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_chitchat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessage.ProtoReflect.Descriptor instead.
func (*BroadcastMessage) Descriptor() ([]byte, []int) {
	return file_grpc_chitchat_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *BroadcastMessage) GetLogicalTimestamp() int64 {
	if x != nil {
		return x.LogicalTimestamp
	}
	return 0
}

func (x *BroadcastMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadcastMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_CHAT
}

var File_grpc_chitchat_proto protoreflect.FileDescriptor

const file_grpc_chitchat_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/chitchat.proto\x12\bchitchat\"e\n" +
	"\vJoinRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\x12+\n" +
	"\x11logical_timestamp\x18\x02 \x01(\x03R\x10logicalTimestamp\"f\n" +
	"\fLeaveRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\x12+\n" +
	"\x11logical_timestamp\x18\x02 \x01(\x03R\x10logicalTimestamp\"\x86\x01\n" +
	"\x12SendMessageRequest\x12)\n" +
	"\x10participant_name\x18\x01 \x01(\tR\x0fparticipantName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12+\n" +
	"\x11logical_timestamp\x18\x03 \x01(\x03R\x10logicalTimestamp\"\xb4\x01\n" +
	"\x10BroadcastMessage\x12\x1f\n" +
	"\vsender_name\x18\x01 \x01(\tR\n" +
	"senderName\x12+\n" +
	"\x11logical_timestamp\x18\x02 \x01(\x03R\x10logicalTimestamp\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x128\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x15.chitchat.MessageTypeR\vmessageType*,\n" +
	"\vMessageType\x12\b\n" +
	"\x04CHAT\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x022\xdc\x01\n" +
	"\x0fChitChatService\x12?\n" +
	"\bJoinChat\x12\x15.chitchat.JoinRequest\x1a\x1a.chitchat.BroadcastMessage0\x01\x12G\n" +
	"\vSendMessage\x12\x1c.chitchat.SendMessageRequest\x1a\x1a.chitchat.BroadcastMessage\x12?\n" +
	"\tLeaveChat\x12\x16.chitchat.LeaveRequest\x1a\x1a.chitchat.BroadcastMessageB\fZ\n" +
	"./chitchatb\x06proto3"

var (
	file_grpc_chitchat_proto_rawDescOnce sync.Once
	file_grpc_chitchat_proto_rawDescData []byte
)

func file_grpc_chitchat_proto_rawDescGZIP() []byte {
	file_grpc_chitchat_proto_rawDescOnce.Do(func() {
		file_grpc_chitchat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_chitchat_proto_rawDesc), len(file_grpc_chitchat_proto_rawDesc)))
	})
	return file_grpc_chitchat_proto_rawDescData
}

var file_grpc_chitchat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_chitchat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_chitchat_proto_goTypes = []any{
	(MessageType)(0),           // 0: chitchat.MessageType
	(*JoinRequest)(nil),        // 1: chitchat.JoinRequest
	(*LeaveRequest)(nil),       // 2: chitchat.LeaveRequest
	(*SendMessageRequest)(nil), // 3: chitchat.SendMessageRequest
	(*BroadcastMessage)(nil),   // 4: chitchat.BroadcastMessage
}
var file_grpc_chitchat_proto_depIdxs = []int32{
	0, // 0: chitchat.BroadcastMessage.message_type:type_name -> chitchat.MessageType
	1, // 1: chitchat.ChitChatService.JoinChat:input_type -> chitchat.JoinRequest
	3, // 2: chitchat.ChitChatService.SendMessage:input_type -> chitchat.SendMessageRequest
	2, // 3: chitchat.ChitChatService.LeaveChat:input_type -> chitchat.LeaveRequest
	4, // 4: chitchat.ChitChatService.JoinChat:output_type -> chitchat.BroadcastMessage
	4, // 5: chitchat.ChitChatService.SendMessage:output_type -> chitchat.BroadcastMessage
	4, // 6: chitchat.ChitChatService.LeaveChat:output_type -> chitchat.BroadcastMessage
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_chitchat_proto_init() }
func file_grpc_chitchat_proto_init() {
	if File_grpc_chitchat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_chitchat_proto_rawDesc), len(file_grpc_chitchat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_chitchat_proto_goTypes,
		DependencyIndexes: file_grpc_chitchat_proto_depIdxs,
		EnumInfos:         file_grpc_chitchat_proto_enumTypes,
		MessageInfos:      file_grpc_chitchat_proto_msgTypes,
	}.Build()
	File_grpc_chitchat_proto = out.File
	file_grpc_chitchat_proto_goTypes = nil
	file_grpc_chitchat_proto_depIdxs = nil
}
